export const ADD_CART_INGREDIENT = 'ADD_CART_INGREDIENT';
export const DELETE_CART_INGREDIENT = 'DELETE_CART_INGREDIENT';
export const ADD_CART_INGREDIENT_BUN = 'ADD_CART_INGREDIENT_BUN';
export const MOVE_CART_INGREDIENT = 'MOVE_CART_INGREDIENT';
export const CLEAR_CART_INGREDIENT = 'CLEAR_CART_INGREDIENT';